version: "3.9"
   
services:
  database:
    image: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - .env.dev
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - database
