# Generated by Django 3.2.11 on 2022-01-23 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('img_path', models.CharField(default='tournament/images/base.jpeg', max_length=100, verbose_name='img_path')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('is_acceptted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('team_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_of_elimination', models.CharField(choices=[('KNOCKOUT', 'KNOCKOUT'), ('GROUP', 'GROUP')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.game')),
                ('referee_list', models.ManyToManyField(blank=True, related_name='referee_list', to=settings.AUTH_USER_MODEL)),
                ('team_list', models.ManyToManyField(blank=True, to='tournament.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_end', models.BooleanField(default=False)),
                ('team_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='tournament.team')),
                ('team_A_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA_score', to='tournament.score')),
                ('team_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='tournament.team')),
                ('team_B_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB_score', to='tournament.score')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('winner_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='tournament.team')),
            ],
        ),
    ]
