# Generated by Django 3.2.11 on 2022-01-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20220129_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_A_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_B_score',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
