# Generated by Django 3.2.11 on 2022-01-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20220131_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(),
        ),
    ]
