# Generated by Django 3.2.11 on 2022-01-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_match_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='tournament.team'),
        ),
    ]
